# Generated by Django 3.2.2 on 2021-05-07 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210507_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='images'),
            preserve_default=False,
        ),
    ]
